[versions]
aboutlibraries = "14.0.0-b02"
android-gradle = "9.0.0"
androidx-activity = "1.12.4"
androidx-appcompat = "1.7.1"
androidx-biometric = "1.4.0-alpha05"
androidx-browser = "1.9.0"
androidx-compose-material = "1.7.3"
androidx-core = "1.17.0"
androidx-coreSplashscreen = "1.2.0"
androidx-datastore = "1.2.0"
androidx-documentfile = "1.1.0"
androidx-lifecycle = "2.10.0-alpha08"
androidx-navigation3 = "1.1.0-alpha04"
androidx-navigationevent = "1.0.0"
androidx-paging = "3.4.1"
androidx-room = "2.8.4"
androidx-sqlite = "2.6.2"
androidx-startup = "1.2.0"
androidx-testCore = "1.7.0"
androidx-testExtJunit = "1.3.0"
androidx-testOrchestrator = "1.6.1"
androidx-testRules = "1.7.0"
androidx-testRunner = "1.7.0"
androidx-window = "1.5.1"
androidx-work = "2.11.1"
buildkonfig = "0.17.1"
coil = "3.3.0"
composables = "1.49.6"
compose-animationGraphics = "1.10.3"
compose-material3 = "1.11.0-alpha02"
compose-material3Adaptive = "1.3.0-alpha04"
compose-runtime = "1.10.0"
compose-ui = "1.10.3"
composeHotReload = "1.0.0"
composeMultiplatform = "1.11.0-alpha02"
detekt = "2.0.0-alpha.2"
detekt-compose = "0.5.6"
dokka = "2.2.0-Beta"
edge2edgePreview = "0.7.1"
filekit = "0.12.0"
java = "21"
jcifs = "3.0.1"
kmpfile = "0.8.0"
kotlin = "2.3.20-Beta2"
kotlinx-collectionsImmutable = "0.4.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.10.0"
kotlinxKover = "0.9.7"
ksp = "2.3.5"
licensee = "1.14.1"
metro = "0.10.2"
modulegraph = "0.13.0"
multiplatform-core = "1.1.0-alpha03"
multiplatform-navigation3 = "1.1.0-alpha02"
navigation3-resultstate = "1.1.6"
rin = "0.4.0"
robolectric = "4.16.1"
sevenzipjbinding = "16.02-2.01"
sevenzipjbinding-android = "16.02-2.4"
slf4j-android = "2.0.17-0"
soil = "1.0.0-alpha15"
squareup-okio = "3.16.4"
targetSdk = "36"
versionCatalogLinter = "1.1.0"

[libraries]
aboutlibraries-compose = { group = "com.mikepenz", name = "aboutlibraries-compose", version.ref = "aboutlibraries" }
aboutlibraries-gradlePlugin = { group = "com.mikepenz.aboutlibraries.plugin", name = "com.mikepenz.aboutlibraries.plugin.gradle.plugin", version.ref = "aboutlibraries" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle" }
androidx-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "androidx-biometric" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidx-browser" }
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-coreSplashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-coreSplashscreen" }
androidx-coreUri = { group = "org.jetbrains.androidx.core", name = "core-uri", version.ref = "multiplatform-core" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
androidx-datastoreCoreOkio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "androidx-datastore" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidx-documentfile" }
androidx-lifecycleCommon = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycleCompose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycleViewmodelCompose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycleViewmodelNavigation3 = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
androidx-navigation3Runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "androidx-navigation3" }
androidx-navigation3UI = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "multiplatform-navigation3" }
androidx-navigationeventCompose = { group = "org.jetbrains.androidx.navigationevent", name = "navigationevent-compose", version.ref = "androidx-navigationevent" }
androidx-pagingCommon = { group = "androidx.paging", name = "paging-common", version.ref = "androidx-paging" }
androidx-pagingCompose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }
androidx-pagingTesting = { group = "androidx.paging", name = "paging-testing", version.ref = "androidx-paging" }
androidx-roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-roomPaging = { group = "androidx.room", name = "room-paging", version.ref = "androidx-room" }
androidx-roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-roomTesting = { group = "androidx.room", name = "room-testing", version.ref = "androidx-room" }
androidx-sqliteBundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "androidx-sqlite" }
androidx-startupRuntime = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidx-startup" }
androidx-testCoreKtx = { group = "androidx.test", name = "core-ktx", version.ref = "androidx-testCore" }
androidx-testExtJunitKtx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidx-testExtJunit" }
androidx-testOrchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "androidx-testOrchestrator" }
androidx-testRules = { group = "androidx.test", name = "rules", version.ref = "androidx-testRules" }
androidx-testRunner = { group = "androidx.test", name = "runner", version.ref = "androidx-testRunner" }
androidx-windowCore = { group = "androidx.window", name = "window-core", version.ref = "androidx-window" }
androidx-workRuntime = { group = "androidx.work", name = "work-runtime", version.ref = "androidx-work" }
coil3 = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil3-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
composables-composeunstyledPrimitive = { group = "com.composables", name = "composeunstyled-primitives", version.ref = "composables" }
compose-animationGraphics = { group = "androidx.compose.animation", name = "animation-graphics", version.ref = "compose-animationGraphics" }
compose-componentsAnimatedimage = { group = "org.jetbrains.compose.components", name = "components-animatedimage", version.ref = "composeMultiplatform" }
compose-componentsResources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "composeMultiplatform" }
compose-edgeToEdgePreview = { group = "de.drick.compose", name = "edge-to-edge-preview", version.ref = "edge2edgePreview" }
compose-gradlePlugin = { group = "org.jetbrains.compose", name = "org.jetbrains.compose.gradle.plugin", version.ref = "composeMultiplatform" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-material3Adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "compose-material3Adaptive" }
compose-material3AdaptiveLayout = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-layout", version.ref = "compose-material3Adaptive" }
compose-material3AdaptiveNavigation3 = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "compose-material3Adaptive" }
compose-material3AdaptiveNavigationSuite = { group = "org.jetbrains.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "compose-material3" }
compose-materialIconsExtended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "androidx-compose-material" }
compose-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "composeMultiplatform" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "composeMultiplatform" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "composeMultiplatform" }
compose-uiBackhandler = { group = "org.jetbrains.compose.ui", name = "ui-backhandler", version.ref = "composeMultiplatform" }
compose-uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-ui" }
compose-uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-ui" }
compose-uiTooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "composeMultiplatform" }
detekt-compose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detekt-compose" }
detekt-gradlePlugin = { group = "dev.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-ktlintWrapper = { group = "dev.detekt", name = "detekt-rules-ktlint-wrapper", version.ref = "detekt" }
dokka-gradlePlugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
filekit = { group = "io.github.vinceglb", name = "filekit-dialogs", version.ref = "filekit" }
filekit-compose = { group = "io.github.vinceglb", name = "filekit-dialogs-compose", version.ref = "filekit" }
jcifs = { group = "org.codelibs", name = "jcifs", version.ref = "jcifs" }
kmpfile-filekit = { group = "dev.zwander", name = "kmpfile-filekit", version.ref = "kmpfile" }
kmpfile-okio = { group = "dev.zwander", name = "kmpfile-okio", version.ref = "kmpfile" }
kotlin-composeCompilerGradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serializationGradlePlugin = { group = "org.jetbrains.kotlin.plugin.serialization", name = "org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-collectionsImmutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collectionsImmutable" }
kotlinx-coroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesSwing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serializationCbor = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-cbor", version.ref = "kotlinx-serialization" }
kotlinx-serializationCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serializationProtobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
kover-gradlePlugin = { group = "org.jetbrains.kotlinx.kover", name = "org.jetbrains.kotlinx.kover.gradle.plugin", version.ref = "kotlinxKover" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
licensee-gradlePlugin = { group = "app.cash.licensee", name = "licensee-gradle-plugin", version.ref = "licensee" }
metro-android = { group = "dev.zacsweers.metro", name = "metrox-android", version.ref = "metro" }
metro-gradlePlugin = { group = "dev.zacsweers.metro", name = "dev.zacsweers.metro.gradle.plugin", version.ref = "metro" }
navigation3-resultstate = { group = "io.github.irgaly.navigation3.resultstate", name = "resultstate", version.ref = "navigation3-resultstate" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "squareup-okio" }
rin = { group = "io.github.takahirom.rin", name = "rin", version.ref = "rin" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
sevenzipjbinding = { group = "net.sf.sevenzipjbinding", name = "sevenzipjbinding", version.ref = "sevenzipjbinding" }
sevenzipjbinding-allPlatforms = { group = "com.github.shayartzi.sevenzipjbinding", name = "sevenzipjbinding-all-platforms", version.ref = "sevenzipjbinding" }
sevenzipjbinding-android = { group = "com.sorrowblue.sevenzipjbinding", name = "7-Zip-JBinding-4Android", version.ref = "sevenzipjbinding-android" }
slf4j-android = { group = "uk.uuid.slf4j", name = "slf4j-android", version.ref = "slf4j-android" }
soil-form = { group = "com.soil-kt.soil", name = "form", version.ref = "soil" }

[bundles]
dokka = [
    "detekt-compose",
    "detekt-ktlintWrapper"
]
plugins = [
    "aboutlibraries-gradlePlugin",
    "android-gradlePlugin",
    "compose-gradlePlugin",
    "detekt-gradlePlugin",
    "dokka-gradlePlugin",
    "kotlin-composeCompilerGradlePlugin",
    "kotlin-gradlePlugin",
    "kotlin-serializationGradlePlugin",
    "kover-gradlePlugin",
    "ksp-gradlePlugin",
    "licensee-gradlePlugin",
    "metro-gradlePlugin"
]

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
androidApplication = { id = "com.android.application", version.ref = "android-gradle" }
androidLibrary = { id = "com.android.library", version.ref = "android-gradle" }
androidMultiplatform = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradle" }
androidxRoom = { id = "androidx.room", version.ref = "androidx-room" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
comicviewer-androidApplication = { id = "comicviewer.convention.android-application" }
comicviewer-androidLibrary = { id = "comicviewer.convention.android-library" }
comicviewer-di = { id = "comicviewer.primitive.metro" }
comicviewer-multiplatformCompose = { id = "comicviewer.convention.multiplatform-compose" }
comicviewer-multiplatformFeature = { id = "comicviewer.convention.multiplatform-feature" }
comicviewer-multiplatformLibrary = { id = "comicviewer.convention.multiplatform-library" }
comicviewer-primitive-aboutlibraries = { id = "comicviewer.primitive.aboutlibraries" }
comicviewer-primitive-detekt = { id = "comicviewer.primitive.detekt" }
comicviewer-primitive-dokka = { id = "comicviewer.primitive.dokka" }
comicviewer-primitive-licensee = { id = "comicviewer.primitive.licensee" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinxKover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinxKover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
licensee = { id = "app.cash.licensee", version.ref = "licensee" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
modulegraph = { id = "dev.iurysouza.modulegraph", version.ref = "modulegraph" }
versionCatalogLinter = { id = "io.github.pemistahl.version-catalog-linter", version.ref = "versionCatalogLinter" }
